version: '3.8'

services:
  # Video Transcoding Application (using DynamoDB - no local database needed)
  app:
    build: .
    container_name: video_transcoder_app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PROVIDER=dynamodb
      - STORAGE_PROVIDER=s3
      - AWS_REGION=ap-southeast-2
      - S3_ORIGINAL_BUCKET=n10992511-videotranscoder-original
      - S3_PROCESSED_BUCKET=n10992511-videotranscoder-processed
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - /opt/ssl:/opt/ssl:ro
    ports:
      - "3000:3000"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Redis Cache (optional, for session management and job queuing)
  redis:
    image: redis:7-alpine
    container_name: video_transcoder_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: video_transcoder_network